@startuml
package Data {
    [SynLeth]
    [OMA]
    [OGEE]
}

node Parser
node Transform
node Visualize
database "Postgres"

Data --> "Parser"
Parser --> "Postgres"
Postgres <-l-> "Transform"
Transform <--> Visualize : get request with gene name

@enduml