@startuml
left to right direction

Entity Gene {
  identifier
  --
  name
  - essentialScore
}
Entity SynLeth {
  geneId1
  geneId2
  --
  score
}
Entity Being {
  id
  --
  name
}

Gene }|--|| Being
SynLeth }|--|| Gene
SynLeth }|--|| Gene
Gene }o--o{ Gene : Mapping
@enduml
